import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) 
{
  return (
    <html lang="en">
      <body>
       <div className="navbar"> 
         <Link href="/"
         className="logo">Home</Link> 
         <Link href="/list">List</Link>
         <Link href="/signup">Signup</Link>
         <Link href="/write">Write</Link>
         <Link href="/File">File</Link> 
         <Link href="/Newspaper">Newspaper</Link> 
         <Link href="/File_search">Search</Link> 
       </div>  
        {children}
      </body>
    </html>
  );
}
